from django.urls import path
from . import views

urlpatterns = [
	path('', views.rage),
    path('A', views.a),
    path('B', views.b),
    path('C', views.c),
    path('D', views.d),
    path('E', views.e),
    path('F', views.f),
    path('G', views.g),
    path('H', views.h),
    path('I', views.i),
    path('J', views.j),
    path('K', views.k),
    path('L', views.l),
    path('M', views.m),
    path('N', views.n),
    path('O', views.o),
    path('r1', views.r1),
    path('r2', views.r2),
    path('r3', views.r3),
    path('r4', views.r4),
    path('r5', views.r5),
    path('r6', views.r6),
    path('r7', views.r7),
    path('r8', views.r8),
    path('r9', views.r9),
    path('r10', views.r10),
    path('r11', views.r11),
    path('r12', views.r12),
    path('r13', views.r13),
    path('r14', views.r14),
    path('r15', views.r15),
    path('r16', views.r16),
]
